# Generated by Django 4.1.2 on 2022-12-01 19:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='requestforlessons',
            options={'ordering': ['-request_created_at']},
        ),
        migrations.AddField(
            model_name='requestforlessons',
            name='request_created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requestforlessons',
            name='availability',
            field=models.CharField(max_length=27),
        ),
    ]
