# Generated by Django 4.1.2 on 2022-12-02 09:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='children',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='parents',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
