# Generated by Django 4.1.2 on 2022-12-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooladmin',
            name='createAdmins',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schooladmin',
            name='deleteAdmins',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schooladmin',
            name='editAdmins',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schooladmin',
            name='editTermDates',
            field=models.BooleanField(default=False),
        ),
    ]
