# Generated by Django 4.1.3 on 2022-11-18 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_remove_user_is_director_user_is_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('bookingCreatedAt', models.TimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.invoice')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.student')),
            ],
            options={
                'ordering': ['-bookingCreatedAt'],
            },
        ),
    ]
