# Generated by Django 4.1.3 on 2022-11-18 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_invoice_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='urn',
            field=models.CharField(default='blank', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
