# Generated by Django 4.1.2 on 2022-11-20 21:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_requestforlessons_fulfilled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestforlessons',
            name='lesson_duration',
            field=models.IntegerField(default=60, validators=[django.core.validators.MinValueValidator(15, message='A lesson must be at least 15 minutes')]),
        ),
    ]
